use_frameworks!

platform :ios, '8.0'

target 'ABWatchSessionManager_Example' do
  pod 'ABWatchSessionManager', :path => '../'

  target 'ABWatchSessionManager_Tests' do
    inherit! :search_paths

    
  end
end
