use_frameworks!

platform :ios, '9.0'

target 'ABWatchSessionManager_Example' do
  pod 'ABWatchSessionManager', :path => '../'

  target 'ABWatchSessionManager_Tests' do
    inherit! :search_paths

    
  end
  
  target 'EampleWatch Extension' do
    platform :watchos, '6.0'
    pod 'ABWatchSessionManager', :path => '../'


  end
end
